Repository alexlancaster/pypop, pull requests merged in 2023-09, with the labels that each got.

#116 clarify tab separations in data files
  website/docs/guide-chapter-usage.rst
Labels: documentation

#113 fix numpy + regex warnings
  src/PyPop/Arlequin.py
  src/PyPop/Haplo.py
  src/PyPop/Utils.py
Labels: bug

#118 End-user warning that undocumented module `[Haplostats]` is not yet supported
  DEV_NOTES.md
  NEWS.rst
  setup.py
  src/PyPop/Main.py
Labels: bug, documentation

#123 Update docs preparing for beta version
  .github/workflows/build_wheels.yml
  README.rst
Labels: documentation

#124 more informative default "placeholder" file names
  src/PyPop/pypop.py
Labels: enhancement, documentation

#125 dynamic generation of number of TSV files based on input
  src/PyPop/Meta.py
  src/PyPop/__init__.py
  src/PyPop/xslt/lib.xsl
  src/PyPop/xslt/meta-to-r.xsl
  tests/base.py
  tests/data/WS_BDCtrl_Test_EM_3_and_4_locus.ini
  tests/data/WS_BDCtrl_Test_EM_5_locus.ini
  tests/data/output/generate_tsv_3_and_4_locus/1-locus-allele.dat
  tests/data/output/generate_tsv_3_and_4_locus/1-locus-summary.dat
  tests/data/output/generate_tsv_3_and_4_locus/3-locus-haplo.dat
  tests/data/output/generate_tsv_3_and_4_locus/3-locus-summary.dat
  tests/data/output/generate_tsv_3_and_4_locus/4-locus-haplo.dat
  tests/data/output/generate_tsv_3_and_4_locus/4-locus-summary.dat
  tests/data/output/generate_tsv_5_locus/1-locus-allele.dat
  tests/data/output/generate_tsv_5_locus/1-locus-summary.dat
  tests/data/output/generate_tsv_5_locus/5-locus-haplo.dat
  tests/data/output/generate_tsv_5_locus/5-locus-summary.dat
  tests/test_AlleleColon.py
  tests/test_Filters.py
  tests/test_GenerateTSV.py
  tests/test_GenotypeCommon.py
  tests/test_Popmeta.py
  tests/test_USAFEL.py
  tests/test_UserGuideExamples.py
Labels: enhancement

#128 Preparation for beta version: update authors, release notes
  .gitattributes
  .github/workflows/build_wheels.yml
  .github/workflows/documentation.yaml
  .zenodo.json
  AUTHORS.rst
  CITATION.cff
  CONTRIBUTING.rst
  NEWS.rst
  README.rst
  pyproject.toml
  src/obsolete/Makefile
  src/obsolete/check-status-tag.sh
  src/obsolete/tag-and-install.sh
  website/conf.py
  website/docs/AUTHORS.rst
  website/docs/guide-chapter-changes.rst
  website/index.rst
Labels: documentation
