Repository alexlancaster/pypop, pull requests merged in 2023-07, with the labels that each got.

#94 adding pypi upload, contribution guide
  .github/workflows/build_wheels.yml
  CONTRIBUTING.rst
  README.rst
  setup.py
  src/PyPop/__init__.py
  website/conf.py
  website/docs/guide-chapter-contributing.rst
  website/docs/guide-chapter-install-obsolete.rst
  website/docs/index.rst
  website/index.rst
Labels: enhancement, documentation

#95 add ALD to guide-chapter-instructions.rst
  website/docs/guide-chapter-instructions.rst
Labels: documentation

#97 Cleanup pairwise locus stats docs
  website/docs/guide-chapter-instructions.rst
  website/docs/guide-chapter-usage.rst
Labels: documentation

#92 Testing adding to install.rst
  website/docs/guide-chapter-usage.rst
Labels: documentation

#100 merge `website/README.md` into `CONTRIBUTORS.rst`
  .github/workflows/documentation.yaml
  CONTRIBUTING.rst
  README.rst
  website/README.md
Labels: documentation

#103 clarify that docs can be build independently of the software
  CONTRIBUTING.rst
Labels: documentation

#61 round all haplotype frequencies to 5 decimal places
  src/PyPop/xslt/emhaplofreq.xsl
Labels: bug

#107 output 2 locus haplotypes in TSV if they are explicitly specified
  src/PyPop/xslt/meta-to-r.xsl
  tests/data/WS_BDCtrl_Test_EM_2_locus.ini
  tests/data/output/generate_tsv_2_locus/1-locus-allele.dat
  tests/data/output/generate_tsv_2_locus/1-locus-genotype.dat
  tests/data/output/generate_tsv_2_locus/1-locus-hardyweinberg.dat
  tests/data/output/generate_tsv_2_locus/1-locus-pairwise-fnd.dat
  tests/data/output/generate_tsv_2_locus/1-locus-summary.dat
  tests/data/output/generate_tsv_2_locus/2-locus-haplo.dat
  tests/data/output/generate_tsv_2_locus/2-locus-summary.dat
  tests/data/output/generate_tsv_2_locus/3-locus-haplo.dat
  tests/data/output/generate_tsv_2_locus/3-locus-summary.dat
  tests/data/output/generate_tsv_2_locus/4-locus-haplo.dat
  tests/data/output/generate_tsv_2_locus/4-locus-summary.dat
  tests/data/output/generate_tsv_2_locus/meta.xml
  tests/test_GenerateTSV.py
Labels: bug
